version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/prod/api.Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}
        - ADMIN_URL=${ADMIN_URL}

        - RDS_USERNAME=${RDS_USERNAME}
        - RDS_PASSWORD=${RDS_PASSWORD}
        - RDS_HOSTNAME=${RDS_HOSTNAME}

        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

        - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
        - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
        - AWS_CF_KEY_PAIR_ID=${AWS_CF_KEY_PAIR_ID}
        - AWS_CF_PRIVATE_KEY=${AWS_CF_PRIVATE_KEY}

        - AWS_MEDIACONVERT_ACCESS_KEY_ID=${AWS_MEDIACONVERT_ACCESS_KEY_ID}
        - AWS_MEDIACONVERT_SECRET_ACCESS_KEY=${AWS_MEDIACONVERT_SECRET_ACCESS_KEY}
        - AWS_MEDIACONVERT_ROLE_ARN=${AWS_MEDIACONVERT_ROLE_ARN}
        - AWS_MEDIACONVERT_ENDPOINT_URL=${AWS_MEDIACONVERT_ENDPOINT_URL}

        - AWS_SNS_ACCESS_KEY_ID=${AWS_SNS_ACCESS_KEY_ID}
        - AWS_SNS_SECRET_ACCESS_KEY=${AWS_SNS_SECRET_ACCESS_KEY}
        - AWS_SNS_TOPIC_ARN=${AWS_SNS_TOPIC_ARN}

        - BOSS_URL=${BOSS_URL}
        - BOSS_SECRET_KEY=${BOSS_SECRET_KEY}

        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
        - STRIPE_PRICE_ID_USD=${STRIPE_PRICE_ID_USD}
        - STRIPE_PRICE_ID_INR=${STRIPE_PRICE_ID_INR}

        - RESEND_API_KEY=${RESEND_API_KEY}
        - RESEND_WEBHOOK_SIGNING_KEY=${RESEND_WEBHOOK_SIGNING_KEY}

        - RDS_DB_NAME=${RDS_DB_NAME}
        - RDS_PORT=${RDS_PORT}
        - CI_CD_STAGE=${CI_CD_STAGE}
        - REDIS_URL=${REDIS_URL}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - AWS_S3_CUSTOM_DOMAIN=${AWS_S3_CUSTOM_DOMAIN}
        - AWS_CDN_BUCKET_NAME=${AWS_CDN_BUCKET_NAME}
        - AWS_INPUT_BUCKET_NAME=${AWS_INPUT_BUCKET_NAME}
        - AWS_OUTPUT_BUCKET_NAME=${AWS_OUTPUT_BUCKET_NAME}

    image: api:latest
    command:
      - python manage.py migrate --noinput
      - python manage.py collectstatic --noinput
      - daphne -b 0.0.0.0 -p 8000 vjournal.asgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    restart: on-failure

  nginx:
    build: docker/prod/nginx
    image: nginx:latest
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - api
    healthcheck:
      test: curl --fail http://localhost/ht/ || exit 1
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s

  celery:
    build:
      context: .
      dockerfile: docker/prod/celery.Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}
        - ADMIN_URL=${ADMIN_URL}

        - RDS_USERNAME=${RDS_USERNAME}
        - RDS_PASSWORD=${RDS_PASSWORD}
        - RDS_HOSTNAME=${RDS_HOSTNAME}

        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

        - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
        - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
        - AWS_CF_KEY_PAIR_ID=${AWS_CF_KEY_PAIR_ID}
        - AWS_CF_PRIVATE_KEY=${AWS_CF_PRIVATE_KEY}

        - AWS_MEDIACONVERT_ACCESS_KEY_ID=${AWS_MEDIACONVERT_ACCESS_KEY_ID}
        - AWS_MEDIACONVERT_SECRET_ACCESS_KEY=${AWS_MEDIACONVERT_SECRET_ACCESS_KEY}
        - AWS_MEDIACONVERT_ROLE_ARN=${AWS_MEDIACONVERT_ROLE_ARN}
        - AWS_MEDIACONVERT_ENDPOINT_URL=${AWS_MEDIACONVERT_ENDPOINT_URL}

        - AWS_SNS_ACCESS_KEY_ID=${AWS_SNS_ACCESS_KEY_ID}
        - AWS_SNS_SECRET_ACCESS_KEY=${AWS_SNS_SECRET_ACCESS_KEY}
        - AWS_SNS_TOPIC_ARN=${AWS_SNS_TOPIC_ARN}

        - BOSS_URL=${BOSS_URL}
        - BOSS_SECRET_KEY=${BOSS_SECRET_KEY}

        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
        - STRIPE_PRICE_ID_USD=${STRIPE_PRICE_ID_USD}
        - STRIPE_PRICE_ID_INR=${STRIPE_PRICE_ID_INR}

        - RESEND_API_KEY=${RESEND_API_KEY}
        - RESEND_WEBHOOK_SIGNING_KEY=${RESEND_WEBHOOK_SIGNING_KEY}

        - RDS_DB_NAME=${RDS_DB_NAME}
        - RDS_PORT=${RDS_PORT}
        - CI_CD_STAGE=${CI_CD_STAGE}
        - REDIS_URL=${REDIS_URL}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - AWS_S3_CUSTOM_DOMAIN=${AWS_S3_CUSTOM_DOMAIN}
        - AWS_CDN_BUCKET_NAME=${AWS_CDN_BUCKET_NAME}
        - AWS_INPUT_BUCKET_NAME=${AWS_INPUT_BUCKET_NAME}
        - AWS_OUTPUT_BUCKET_NAME=${AWS_OUTPUT_BUCKET_NAME}

    image: celery:latest
    command: celery -A vjournal worker -l INFO --uid=nobody --gid=nogroup -Q celery
    volumes:
      - .:/usr/src/app
    restart: on-failure
    depends_on:
      - nginx

  beat:
    build:
      context: .
      dockerfile: docker/prod/beat.Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}
        - ADMIN_URL=${ADMIN_URL}

        - RDS_USERNAME=${RDS_USERNAME}
        - RDS_PASSWORD=${RDS_PASSWORD}
        - RDS_HOSTNAME=${RDS_HOSTNAME}

        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

        - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
        - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
        - AWS_CF_KEY_PAIR_ID=${AWS_CF_KEY_PAIR_ID}
        - AWS_CF_PRIVATE_KEY=${AWS_CF_PRIVATE_KEY}

        - AWS_MEDIACONVERT_ACCESS_KEY_ID=${AWS_MEDIACONVERT_ACCESS_KEY_ID}
        - AWS_MEDIACONVERT_SECRET_ACCESS_KEY=${AWS_MEDIACONVERT_SECRET_ACCESS_KEY}
        - AWS_MEDIACONVERT_ROLE_ARN=${AWS_MEDIACONVERT_ROLE_ARN}
        - AWS_MEDIACONVERT_ENDPOINT_URL=${AWS_MEDIACONVERT_ENDPOINT_URL}

        - AWS_SNS_ACCESS_KEY_ID=${AWS_SNS_ACCESS_KEY_ID}
        - AWS_SNS_SECRET_ACCESS_KEY=${AWS_SNS_SECRET_ACCESS_KEY}
        - AWS_SNS_TOPIC_ARN=${AWS_SNS_TOPIC_ARN}

        - BOSS_URL=${BOSS_URL}
        - BOSS_SECRET_KEY=${BOSS_SECRET_KEY}

        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
        - STRIPE_PRICE_ID_USD=${STRIPE_PRICE_ID_USD}
        - STRIPE_PRICE_ID_INR=${STRIPE_PRICE_ID_INR}

        - RESEND_API_KEY=${RESEND_API_KEY}
        - RESEND_WEBHOOK_SIGNING_KEY=${RESEND_WEBHOOK_SIGNING_KEY}

        - RDS_DB_NAME=${RDS_DB_NAME}
        - RDS_PORT=${RDS_PORT}
        - CI_CD_STAGE=${CI_CD_STAGE}
        - REDIS_URL=${REDIS_URL}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - AWS_S3_CUSTOM_DOMAIN=${AWS_S3_CUSTOM_DOMAIN}
        - AWS_CDN_BUCKET_NAME=${AWS_CDN_BUCKET_NAME}
        - AWS_INPUT_BUCKET_NAME=${AWS_INPUT_BUCKET_NAME}
        - AWS_OUTPUT_BUCKET_NAME=${AWS_OUTPUT_BUCKET_NAME}

    image: beat:latest
    command: celery -A vjournal beat -l info
    volumes:
      - .:/usr/src/app
    restart: on-failure
    depends_on:
      - nginx
