# Generated by Django 4.2.2 on 2023-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customer',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
