# Generated by Django 4.2.2 on 2023-06-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_rename_input_height_video_input_height_in_px_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='output_height_in_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='output_width_in_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
