# Generated by Django 4.2.2 on 2023-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='input_height',
            field=models.PositiveIntegerField(default=480),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='input_width',
            field=models.PositiveIntegerField(default=640),
            preserve_default=False,
        ),
    ]
