# Generated by Django 4.2.2 on 2023-06-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_output_height_in_px_video_output_width_in_px'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='status',
        ),
    ]
