# Generated by Django 4.2.2 on 2023-06-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0008_alter_video_options_remove_thumbnail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitles',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
