# Generated by Django 4.2.2 on 2023-06-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_subtitles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitles',
            name='token_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
