# Generated by Django 4.2.2 on 2023-06-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitles',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Subtitles'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Thumbnails'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Videos'},
        ),
    ]
