# Generated by Django 4.2.2 on 2023-07-02 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_rename_email_vemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VEmail',
            new_name='Email',
        ),
    ]
